dependencies:
  - python=3
  - pip3:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - sklearn
    - datetime
    - seaborn
    - keras
    - math
    - plotly
    - tensorflow
